### ISSUE TITLE
Section header that spans out over multiple columns

### ISSUE THREAD

**Issue by jbouaziz** [stuffrabbit/SwiftSpreadsheet#10]
Hello, great work on the library and the fact that it relies on native `UICollectionView` system is great.

I'm trying to create "grouped headers" that can span over muliple columns like in the screenshot below. How would you approach it?
![image](https://user-images.githubusercontent.com/3008860/92471746-b92a2b80-f1d8-11ea-95b9-2455dea534c7.png)

I was thinking about adding a large section header but the width of headers column is tied to the width of row's columns.

**Comment by stuffrabbit** [comment]
Hi Jonathan,
thanks for using this lib, I'm glad you like it! 

I am afraid that this grouped section feature is not supported by this library. One thing you could do is to extend the current layout and add decoration views above the section headers, or change the supplementary views that are used for each column/row to span over multiple columns.

In any case, you will have to update the core layout itself.

Hope this helps,
Wojtek

**Comment by jbouaziz** [comment]
I see, I was thinking of adding some kind of "number of columns for section" property but I think that your solution might work better.

Thanks for the advice @stuffrabbit.
