### ISSUE TITLE
UICollectionView received layout attributes for a cell with an index path that does not exist: <NSIndexPath: 0x60000003ba40>

### ISSUE THREAD

**Issue by niravdesai** [stuffrabbit/SwiftSpreadsheet#3]
if numberofrows in section are different it crashes.

**Comment by stuffrabbit** [comment]
Hey,
different of what? Can you provide the data you have implemented and that causes this crash? And you certainly mean the `numberOfItems(inSection: section)` method, correct?

**Comment by niravdesai** [comment]
Yes number of rows in section is different then it doesn't work.

**Comment by stuffrabbit** [comment]
Please provide your example code

**Comment by james-rant** [comment]
I know this is an old issue, but I just came up against this problem myself. The solution is to call `resetLayoutCache()` after calling `reloadData()` if the datasource will have a different amount of rows/sections.
