### ISSUE TITLE
DecorativeView

### ISSUE THREAD

**Issue by bdhaeseleer** [stuffrabbit/SwiftSpreadsheet#6]
I'm pretty sure this is a dumb question, but is there a way to update/set the label into a decorative view programmatically ? 
I didn't find any example about it in the project and I don't understand how I may access to the label in order to change "Revenue" by something else

Thanks in advance

**Comment by stuffrabbit** [comment]
Hey, the question isn’t dumb at all. Unfortunately, there is no way of simply updating  decoration views once they are set. You could try to Invalide/initialize a new collection view layout and assign it to your collection view (this would mean that everything gets redrawn) anytime you want to change the decoration view. But I am not sure if this works properly. Hope this helps. 

Best regards
Wojtek

**Comment by bdhaeseleer** [comment]
Thanks for you answer, actually I based my solution on : https://stackoverflow.com/a/39218108 .
This isn't very modular but it works in my case where I only need a topLeft decoration.

**Comment by stuffrabbit** [comment]
That looks interesting. Thanks for the hint.
